In [1]:
import matplotlib.pyplot as plt
import numpy as np
import random

In [2]:
t4=np.array(range(1,4),dtype=int
#t4=np.array(range(1,4),dtype="i1"
t4 = np.array(range(1,4),dtype="int8")

SyntaxError: invalid syntax (<ipython-input-2-344d59cba605>, line 3)

In [3]:
print(t4)
print(t4.dtype)

NameError: name 't4' is not defined

In [4]:
t5=np.array(range(10),dtype=float)
print(t5)
print(t5.dtype)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
float64


In [5]:
#创建bool类型
t6=np.array([0,1,0,1,1],dtype=bool)
print(t6)
print(t6.dtype)

[False  True False  True  True]
bool


In [6]:
#调整数据类型
t7 = t6.astype("int8")
print(t7)
print(t7.dtype)


[0 1 0 1 1]
int8


In [7]:
#numpy中的小数
t8=np.array([random.random() for i in range(10)])
print(t8)
print(t8.dtype)

[0.42056746 0.2217182  0.29315298 0.12383958 0.36022987 0.77367093
 0.31949443 0.64504375 0.25892865 0.52297601]
float64


In [8]:
t9=np.round(t8,2)
print(t9)
print(t9.dtype)

[0.42 0.22 0.29 0.12 0.36 0.77 0.32 0.65 0.26 0.52]
float64
